trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@4
      displayName: 'Maven pom.xml'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'install'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: Docker@0 
      displayName: 'Build an image' 
      inputs: 
        azureSubscription: 'Visual Studio Professional Subscription (fcd03eb0-274e-4d90-853f-403957855c74)' 
        azureContainerRegistry: '{"loginServer":"soacheiofertas1.azurecr.io", "id" : "/subscriptions/fcd03eb0-274e-4d90-853f-403957855c74/resourceGroups/resource_main/providers/Microsoft.ContainerRegistry/registries/soacheiofertas1"}'

    - task: AzureCLI@2
      displayName: 'Authenticate to Azure Container Registry'
      inputs:
        azureSubscription: 'Visual Studio Professional Subscription (fcd03eb0-274e-4d90-853f-403957855c74)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az acr login --name soacheiofertas1 --username soacheiofertas1 --password qP3Xi++h9dab0MNtkcv90PCYVlyKNkHwvZp1mmZwTU+ACRDSoKop'
      
    - task: Docker@0
      displayName: 'Push an image'
      inputs:
        azureSubscription: 'Visual Studio Professional Subscription (fcd03eb0-274e-4d90-853f-403957855c74)'
        azureContainerRegistry: '{"loginServer":"soacheiofertas1.azurecr.io", "id" : "/subscriptions/fcd03eb0-274e-4d90-853f-403957855c74/resourceGroups/resource_main/providers/Microsoft.ContainerRegistry/registries/soacheiofertas1"}'
        action: 'Push an image'

