trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@4
      displayName: 'Maven pom.xml'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'install'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: Docker@0 
      displayName: 'Build an image' 
      inputs: 
        azureSubscription: 'Visual Studio Professional Subscription (fcd03eb0-274e-4d90-853f-403957855c74)' 
        azureContainerRegistry: '{"loginServer":"soacheiofertas1.azurecr.io", "id" : "/subscriptions/fcd03eb0-274e-4d90-853f-403957855c74/resourceGroups/resource_main/providers/Microsoft.ContainerRegistry/registries/soacheiofertas1"}'
    - task: Docker@2
      displayName: 'Push an image'
      inputs:
        containerRegistry: 'soacheiofertas1.azurecr.io'
        repository: 'soacheiofertas1'
        command: 'push'
        tags: '$(0.1)'
