trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@4
      displayName: 'Maven pom.xml'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'install'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: Docker@2
      displayName: 'Build an image'
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: $(imageName)
        tags: |
          $(tag)

    - script: |
        echo $('eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkNPQVU6UERZSDo0SVJYOjM2SEI6TFYzUDpWNFBGOko0NzQ6SzNOSjpPS1JCOlRZQUo6NEc0Szo1Q1NEIn0.eyJqdGkiOiJhNDQ5YzcxNC0yNDFhLTRhOTctOTU4ZS1kYzc0NzU2OTMwMmQiLCJzdWIiOiJkLmxpc2JvYS5naWdsaW9saUBhdmFuYWRlLmNvbSIsIm5iZiI6MTY4NTc1NzEyOSwiZXhwIjoxNjg1NzY4ODI5LCJpYXQiOjE2ODU3NTcxMjksImlzcyI6IkF6dXJlIENvbnRhaW5lciBSZWdpc3RyeSIsImF1ZCI6InNvYWNoZWlvZmVydGFzMS5henVyZWNyLmlvIiwidmVyc2lvbiI6IjEuMCIsInJpZCI6ImQ1YTJjNWIzYmQ2ZjRlYmI5YTFlYTk3NzhlNThhNWI3IiwiZ3JhbnRfdHlwZSI6InJlZnJlc2hfdG9rZW4iLCJhcHBpZCI6IjA0YjA3Nzk1LThkZGItNDYxYS1iYmVlLTAyZjllMWJmN2I0NiIsInRlbmFudCI6ImNmMzYxNDFjLWRkZDctNDVhNy1iMDczLTExMWY2NmQwYjMwYyIsInBlcm1pc3Npb25zIjp7IkFjdGlvbnMiOlsicmVhZCIsIndyaXRlIiwiZGVsZXRlIiwiZGVsZXRlZC9yZWFkIiwiZGVsZXRlZC9yZXN0b3JlL2FjdGlvbiJdLCJOb3RBY3Rpb25zIjpudWxsfSwicm9sZXMiOltdfQ.x-D3fdPeBD5BHhR0Xn1ke61ixd_k_L4W89J2EbOVk4rEDLYMJfdgnkkn8CUuXz1CSE-JKFOY-O6z6FkvW_eXR9GPFYqbbESG-I8UuZUGdMDwqkSq0dFE6eviRatI22u7Xvt8j0rAe_RU9qQGFFFA2Q_wxlgPaAtEP879IpRujE9vIExKfdyFgb0OZgP8gpfJHVQUKQYsWF4jCdnD3VwqP4G93rQpyTpYjWXdpAwRSOuL7c1dwX3_x6UijsbUHV_lFatfnW7fgyRYQSF9Akaq3TI1SwxH7EoepAXqHVRW4BBKbcYB2NTeKxaPCZPrsxO9jRdEoVpAWMo_ulSf2ZJAbQ') | docker login soacheiofertas1.azurecr.io --username _ --password-stdin
      displayName: 'Authenticate to Azure Container Registry'

    - task: Docker@2
      displayName: 'Push an image'
      inputs:
        command: push
        azureSubscriptionEndpoint: 'Visual Studio Professional Subscription (fcd03eb0-274e-4d90-853f-403957855c74)'
        azureContainerRegistry: 'soacheiofertas1.azurecr.io'
        imageName: $(imageName)
        includeLatestTag: true
