trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@4
      displayName: 'Maven pom.xml'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'install'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: Docker@0
      displayName: 'Build an image'
      inputs:
        azureSubscription: 'Visual Studio Professional Subscription (fcd03eb0-274e-4d90-853f-403957855c74)'
        azureContainerRegistry: 'soacheiofertas1.azurecr.io'
        command: 'build'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: $(imageName)
        tags: |
          $(tag)

    - task: Docker@0
      displayName: 'Push an image'
      inputs:
        azureSubscription: 'Visual Studio Professional Subscription (fcd03eb0-274e-4d90-853f-403957855c74)'
        azureContainerRegistry: 'soacheiofertas1.azurecr.io'
        command: 'push'
        imageName: $(imageName)
        includeLatestTag: true
