apiVersion : apps/v1
kind: Deployment
metadata:
  name: springbootapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbootapp
  template:
    metadata:
      labels:
        app: springbootapp 
    spec:
      containers:
        - name: springbootapp 
          image: soacheiofertas1.azurecr.io/springbootapp
          ports:
          - containerPort: 80